### PR TITLE
Fix bug when describing error of non json body

### PR DESCRIPTION
**Pull request by mt3593**

### CODE REVIEW

**Comment by joelittlejohn** [comment]
What's the bug? :slightly_smiling_face:

**Comment by mt3593** [comment]
Hay @joelittlejohn !

Sorry forgot to give it more context, my bad.

So try this out with the current version:
```clojure
(let [resource-path "/some/resource/path"
       url (local-path resource-path)]
   (rest-driven
        [{:method :POST
          :url resource-path
          :body [#(= "Hi" %) "application/text"]}
         {:status 204}
 
         {:method :POST
          :url resource-path
          :body [#(= "not-hi" %) "application/text"]}
         {:status 204}]
        (http/post url {:content-type "application/text"
                              :body "not-hi"
                              :throw-exceptions false})
        (http/post url {:content-type "application/text"
                              :body "Hi"
                              :throw-exceptions false})))
```
It fails but if you switch the call order it passes! 
The reason for this is that when rest-driver fails on an expectation it tries read the body into json [this bit](https://github.com/whostolebenfrog/rest-cljer/blob/master/src/rest_cljer/core.clj#L44), as the body is not json it throws a parser exception. 

So what you end up with is a filing message about parsing json, not ideal.

The fix is to check if the body given was a `fn` or `map` if map `try` to parse the actual body given. If `fn` just give the `fn` and actual body back.

I've also added the logging in the test scope to help when isolating the issues, hope that's ok, I found it really useful.

**Comment by whostolebenfrog** [comment]
Hi @mt3593. Good fix, thanks for submitting this!

I'm happy to merge the fix but I think we need to remove all the logging dependencies. I don't think it's reasonable for a testing framework to impose it's views on how to log into a project that uses it. Even though it's a test dependency I think that's going a bit too far. 

You should be able to use clojure.tools.logging from core and this will interop with timbre / slf4f / etc.

Would you be able to rebase without the logging? Sorry!

**Comment by mt3593** [comment]
yeah no worries mate, i'll do that now :)

**Comment by whostolebenfrog** [comment]
Thanks @mt3593 - I've merged and released. Latest version is `0.2.1` Thanks for fixing bugs!

**Pull request merged**
